package com.synergybridge;

import io.quarkiverse.mcp.server.Prompt;
import io.quarkiverse.mcp.server.PromptArg;
import io.quarkiverse.mcp.server.PromptMessage;
import jakarta.enterprise.context.ApplicationScoped;

@ApplicationScoped
public class EnterprisePrompts {

    @Prompt(description = "Generate a satirical enterprise consulting report on a given topic")
    PromptMessage enterpriseConsultingReport(
            @PromptArg(description = "The consulting topic, e.g. 'microservices migration'") String topic) {

        String template = """
                You are a senior enterprise consultant at SynergyBridge Solutions. \
                Write a satirical consulting report on the topic: "%s".

                The report MUST follow this enterprise-approved template:

                # Enterprise Strategic Assessment Report
                ## Topic: %s
                ## Classification: CONFIDENTIAL - BOARD EYES ONLY
                ## Prepared by: SynergyBridge Enterprise Solutions Division

                ### 1. Executive Summary
                (Write a paragraph full of buzzwords that says nothing concrete. \
                Reference "digital transformation", "synergy", and "paradigm shift" at least once each.)

                ### 2. Current State Analysis
                (Describe the client's situation as if everything is on fire, but use \
                only passive voice and euphemisms. Never say "broken" — say "presents \
                opportunities for optimization".)

                ### 3. Recommended Solution
                (Recommend buying more enterprise middleware. Reference at least three \
                technologies from the 2000s: WebSphere, TIBCO, Siebel CRM, PeopleSoft, \
                or Informatica. Suggest a 3-year implementation timeline.)

                ### 4. Risk Assessment
                (List risks but immediately dismiss each one. Include "The risk of NOT \
                doing this is greater than the risk of doing it.")

                ### 5. Budget Estimate
                (Provide a suspiciously round number in the millions. Add a footnote that \
                says "±200%% depending on requirements changes".)

                ### 6. Next Steps
                (Schedule more meetings. Recommend forming a steering committee, a \
                governance board, and a Center of Excellence. None of these should \
                have decision-making authority.)

                End with: "This document was auto-generated by SynergyBridge MCP — \
                because the future was supposed to be simpler, but here we are."
                """.formatted(topic, topic);

        return PromptMessage.withUserRole(template);
    }
}
